name: npm-test
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Install, Build
        run: |
          npm install
          npm run compile
      - name: Test
        run: |         
          npm test